# Use DecapBridge PKCE auth (required)
backend:
  name: git-gateway
  repo: TTO-LUCAS/Hazel_Family_Law
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/446a773f-2775-4295-87de-2e66e363b9d1/pkce
  auth_token_endpoint: /sites/446a773f-2775-4295-87de-2e66e363b9d1/token
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://hazelfamilylaw.com.au

media_folder: "public/uploads" # Location where files will be stored in the repo
public_folder: "/uploads" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    media_library:
    config:
      max_file_size: 2621440 # 2.5 MB limit
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Hero Image", name: "hero-image", widget: "image" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Useful Links", name: "useful-links", widget: "list", allow_add: true, required: false, field: { label: "Link", name: "link", widget: "object", fields: [ { label: "Link Text", name: "link-text", widget: "string" }, { label: "URL", name: "url", widget: "string" } ] } }
      - { label: "Accreditation", name: "accreditation-images", widget: "list", allow_add: true, required: false, field: { label: "Accreditation Image", name: "accreditation-image", widget: "image" } }
  - name: "featured blog"
    label: "Featured Blog Post"
    files:
      - name: "featured-post"
        label: "Featured Blog Post"
        file: "src/content/featured-blog/index.md"
        fields:
          - { label: "Select Featured Post", name: "featured-post", widget: "relation", 
              collection: "blog", search_fields: ["title"], 
              value_field: "{{slug}}", display_fields: ["title"] }
  - name: "employees"
    label: "Employees"
    folder: "src/content/employees"
    create: true
    media_library:
      config:
        max_file_size: 2621440 # 2.5 MB limit
        multiple: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Pronouns", name: "pronouns", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Phone", name: "phone", widget: "string", required: false }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Accreditation", name: "accreditation-images", widget: "list", allow_add: true, required: false, field: { label: "Accreditation Image", name: "accreditation-image", widget: "image" } }
  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: true
    media_library:
    config:
      max_file_size: 2621440 # 2.5 MB limit
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Accreditation", name: "accreditation-images", widget: "list", allow_add: true, required: false, field: { label: "Accreditation Image", name: "accreditation-image", widget: "image" } }
  - name: "testimonials"
    label: "Testimonials"
    folder: "src/content/testimonials"
    create: true
    fields:
      - { label: "Client Name", name: "client-name", widget: "string" }
        - { label: "Testimonial", name: "testimonial", widget: "text", maxlength: 50 }
